spring.application.name=FuenteEstatica
server.port=8082
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.url=jdbc:mysql://localhost:3306/fuenteEstatica_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Exponer todos los endpoints de Actuator (incluye /actuator/metrics)
management.endpoints.web.exposure.include=*

# Habilitar Datadog
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.api-key=e106ceff48cb70c8b2cc1a183c2cb02d
management.datadog.metrics.export.site=us5.datadoghq.com
management.datadog.metrics.export.step=10s

# Identificadores del servicio (opcional pero recomendado)
dd.service=estatica
dd.env=dev