spring.application.name=FuenteEstatica
server.port=8082
# Tamaño máximo de un archivo individual
spring.servlet.multipart.max-file-size=50MB

# Tamaño máximo del request completo (todos los archivos juntos)
spring.servlet.multipart.max-request-size=50MB
