@startuml

component "Servicio de Agregación" as Agregador {
  component "Servicio de Solicitudes" as ServicioSolicitudes
  component "Servicio de Fuente Estática" as FuenteEstatica
}

database "Repo de Hechos General" as DBHechosGeneral

component "Servicio de Fuente Dinámica" as FuenteDinamica
component "Servicio de Fuente Proxy" as FuenteProxy
component "Detector de Spam" as DetectorSpam

package "Fuentes Externas" {
  database "Dataset CSV" as CSV
  [API Pública DDSI] as APIDDSI
  [Instancia MetaMapa Remota] as OtraMetaMapa
}

database "Repo de Hechos Dinámicos" as DBHechosDinamicos
database "Repo de Hechos Estáticos" as DBHechosEstaticos
database "Repo de Solicitudes" as DBSolicitudes
database "Repo de Colecciones" as DBColecciones
database "Repo de Hechos" as DBHechosEstaticos

Agregador --> FuenteDinamica : Consulta hechos
Agregador --> FuenteEstatica : Consulta hechos
Agregador --> FuenteProxy : Consulta hechos en tiempo real
Agregador --> DBSolicitudes : Consulta solicitudes
Agregador --> DBColecciones : Consulta colecciones
Agregador --> DBHechosGeneral

FuenteDinamica --> DBHechosDinamicos : Persistencia en memoria
FuenteEstatica --> DBHechosEstaticos : Lectura desde CSV
ServicioSolicitudes --> DBSolicitudes : Guarda solicitudes
ServicioSolicitudes --> DetectorSpam : Verifica spam
ServicioSolicitudes --> Agregador : Solicita ocultar hechos eliminados
FuenteEstatica --> CSV : Lee hechos
FuenteProxy --(0-- APIDDSI
FuenteProxy --(0-- OtraMetaMapa

@enduml
