@startuml


interface IFiltroHecho {
  +aplica(Hecho): boolean
}

class FiltroCategoria implements IFiltroHecho {
  -categoriaBuscada: String
  +aplica(Hecho): boolean
}

class FiltroFechaAcontecimientoDesde implements IFiltroHecho {
  -fechaDesde: LocalDateTime
  +aplica(Hecho): boolean
}

class FiltroFechaAcontecimientoHasta implements IFiltroHecho {
  -fechaHasta: LocalDateTime
  +aplica(Hecho): boolean
}

class FiltroFechaDesde implements IFiltroHecho{
  -fechaLimite: LocalDateTime
  +aplica(Hecho): boolean
}

class FiltroFechaHasta implements IFiltroHecho {
  -fechaLimite: LocalDateTime
  +aplica(Hecho): boolean
}

class FiltroUbicacion implements IFiltroHecho {
  -latitudEsperada: double
  -longitudEsperada: double
  +aplica(Hecho): boolean
}

class Categoria {
    - String nombre;
}

class Coleccion {
    - String titulo;
    - String descripcion;
    - String handle;
    - List<Hecho> hechos;
    - List<Criterio> criterioDePertenencia;
}

interface Criterio {
    + boolean cumple(Hecho unHecho);
}

enum EstadoSolicitudEliminacion {
    PENDIENTE,
    APROBADA,
    RECHAZADA,
}

class Hecho {
    - Integer id;
    - String titulo;
    - String descripcion;
    - Categoria categoria;
    - LocalDateTime fechaHecho;
    - LocalDateTime createdAt;
    - LocalDateTime updatedAt;
    - double latitud;
    - double longitud;
}

class SolicitudEliminacion {
    - UUID id;
    - String justificacionDeEliminacion;
    - Hecho hecho;
    - EstadoSolicitudEliminacion estado;
    - LocalDateTime fechaSolicitud;
}

Hecho --> Categoria
IFiltroHecho ..> Hecho
Coleccion --> "*" Hecho
Coleccion --> "*" Criterio
Criterio ..> Hecho
SolicitudEliminacion --> EstadoSolicitudEliminacion
SolicitudEliminacion--> Hecho

@enduml
