@startuml
/'------------------------------------------------ PACKAGE MODELS -------------------------------------------------------------'/
/'------------------------------------------ EMPIEZA PACKAGE ENTITIES -------------------------------------------------------------'/
/'------------------------------------------------ PACKAGE HECHO -------------------------------------------------------------'/
class Hecho {
    - id : Integer
    - titulo : String
    - descripcion : String
    - categoria : Categoria
    - fechaDeAcontecimiento : LocalDate
    - fechaDeCarga : LocalDateTime
    - lugar : Lugar
    - origen : OrigenDelHecho
    - solicitudesDeEliminacion : List<Solicitud>
    - esAnonimo : Boolean
    - etiquetas : List<Etiqueta>
    - multimedia : List<Multimedia>
    - fueEliminado : Boolean
    - contribuyente : Usuario
    - revision : Revision
}

class Categoria {
    - nombre : String
}

enum EstadoRevision {
    PENDIENTE,
    ACEPTADO,
    RECHAZADO
}

class Etiqueta {
    - nombre : String
    - descripcion : String
}

class Lugar {
    - latitud : Double
    - longitud : Double
}

class Multimedia {
    - rutaAlArchivo : String
}

enum OrigenDelHecho {
    FUENTEDINAMICA,
    FUENTEESTATICA,
    FUENTEPROXY
}

class Revision {
    - estado : EstadoRevision
    - comentario : String

    + estaPendiente() : boolean
}

/'------------------------------------------------ TERMINA PACKAGE HECHO -------------------------------------------------------------'/

/'------------------------------------------------ EMPIEZA PACKAGE SOLICITUD -------------------------------------------------------------'/
class Solicitud {
    - id : Integer
    - justificacionDeEliminacion : String
    - hecho : Hecho
    - estado : EstadoDeSolicitudDeEliminacion
    - fechaSolicitud : LocalDateTime
    - fechaDeEvaluacionDeSolicitud : LocalDateTime
    - visitanteQueCargoSolicitud : Usuario
    - historialSolicitud : List<HistorialSolicitud>
}

class HistorialSolicitud {
    - estado : EstadoDeSolicitudDeEliminacion
    - fechaModificacion : LocalDateTime
    - usuarioModificador : Usuario
}

enum EstadoDeSolicitudDeEliminacion {
    PENDIENTE,
    RECHAZADA,
    APROBADA
}

/'------------------------------------------------ TERMINA PACKAGE SOLICITUD -------------------------------------------------------------'/


/'------------------------------------------------ EMPIEZA PACKAGE COLECCION -------------------------------------------------------------'/
class Coleccion {
    - titulo : String
    - descripcion : String
    - handle : String
    - hechos : List<Hecho>
}

class VerificadorDeCriterios {
    + cumpleCategoria(Hecho hecho, Categoria categoria) : boolean
    + cumpleLugar(Hecho hecho, Lugar lugar) : boolean
    + entreFechas(Hecho hecho, LocalDate desde, LocalDate hasta) : boolean
}

interface Criterio {
    + cumple(Hecho hecho) : boolean
}
/'------------------------------------------------ TERMINA PACKAGE COLECCION -------------------------------------------------------------'/

/'------------------------------------------------ EMPIEZA PACKAGE CRITERIOS -------------------------------------------------------------'/
class CriterioCategoria implements Criterio {
    - categoria : Categoria
    + cumple(Hecho hecho) : boolean
}

class CriterioFechaEntre implements Criterio {
    - desde : LocalDate
    - hasta : LocalDate
    + cumple(Hecho hecho) : boolean
}

class CriterioLugar implements Criterio {
    - lugar : Lugar
    + cumple(Hecho hecho) : boolean
}

/'------------------------------------------------ TERMINA PACKAGE CRITERIOS -------------------------------------------------------------'/

/'------------------------------------------------ EMPIEZA PACKAGE ROLES -------------------------------------------------------------'/
class Usuario {
    - nombre : String
    - rol : IRol
    - solicitudesService : ISolicitudesService

    + solicitarEliminacionDeUnHecho(String unaJustificacion, Hecho unHecho) : void
    + aprobarSolicitud(Solicitud unaSolicitud) : void
    + rechazarSolicitud(Solicitud unaSolicitud) : void
}

interface IRol {
    + tenesPermiso(Permiso permiso) : boolean
}

class Revisor implements IRol {
    + tenesPermiso(Permiso permiso) : boolean
}

class VisitanteAnonimo implements IRol {
    + tenesPermiso(Permiso permiso) : boolean
}

class VisitanteRegistrado implements IRol {
    + tenesPermiso(Permiso permiso) : boolean
}

enum Permisos {
    VER_HECHOS,
    SUBIR_HECHO,
    EDITAR_HECHO,
    ELIMINAR_HECHO,
    REVISAR_HECHO,
    IMPORTAR_HECHOS,
    VER_COLECCIONES,
    CREAR_COLECCION,
    EDITAR_COLECCION,
    ELIMINAR_COLECCION,
    GESTIONAR_ETIQUETAS,
    SOLICITAR_ELIMINACION,
    VER_SOLICITUDES,
    GESTIONAR_SOLICITUDES
}
/'------------------------------------------------ TERMINA PACKAGE ROLES -------------------------------------------------------------'/
/'------------------------------------------------ TERMINA PACKAGE ENTITIES -------------------------------------------------------------'/

/'------------------------------------------------ EMPIEZA PACKAGE FUENTES -------------------------------------------------------------'/
interface FuenteDeHechos {
    + obtenerHechos() : List<Hecho>
}

class FuenteDinamica implements FuenteDeHechos {
    - webClient : WebClient
    + obtenerHechos() : List<Hecho>
}

class FuenteEstatica implements FuenteDeHechos {
    - webClient : WebClient
    + obtenerHechos() : List<Hecho>
}

class FuenteProxy implements FuenteDeHechos {
    - restTemplate : RestTemplate
    - url : String
    + obtenerHechos() : List<Hecho>
}

/'------------------------------------------------ TERMINA PACKAGE FUENTES -------------------------------------------------------------'/
/'------------------------------------------------ EMPIEZA PACKAGE SPAM -------------------------------------------------------------'/
interface DetectorDeSpam {
    + esSpam(String texto) : boolean
}

class DetectorDeSpamImpl implements DetectorDeSpam {
    + esSpam(String texto) : boolean
}
/'------------------------------------------------ TERMINA PACKAGE SPAM -------------------------------------------------------------'/


/'------------------------------------------------ RELACIONES -------------------------------------------------------------'/

'------------------------- RELACIONES ENTRE CLASES -------------------------'

' Relaciones del paquete HECHO
Hecho --> Categoria : categoria
Hecho --> Lugar : lugar
Hecho --> OrigenDelHecho : origen
Hecho --> Usuario : contribuyente
Hecho --> Revision : revision
Hecho --> Etiqueta : etiquetas *
Hecho --> Multimedia : multimedia *
Hecho --> Solicitud : solicitudesDeEliminacion *

' Relaciones del paquete SOLICITUD
Solicitud --> Hecho : hecho
Solicitud --> Usuario : visitanteQueCargoSolicitud
Solicitud --> HistorialSolicitud : historialSolicitud *

HistorialSolicitud --> Usuario : usuarioModificador
HistorialSolicitud --> EstadoDeSolicitudDeEliminacion : estado

' Relaciones del paquete COLECCION
Coleccion --> Hecho : hechos *

VerificadorDeCriterios --> Hecho
VerificadorDeCriterios --> Categoria
VerificadorDeCriterios --> Lugar

CriterioCategoria --> Categoria : categoria
CriterioLugar --> Lugar : lugar

' Relaciones del paquete ROLES
Usuario --> IRol : rol


VisitanteAnonimo --> Permisos
VisitanteRegistrado --> Permisos
Revisor --> Permisos

Hecho --> EstadoRevision








@enduml