@startuml
/'------------------------------------------------ PACKAGE MODELS -------------------------------------------------------------'/
/'------------------------------------------ EMPIEZA PACKAGE ENTITIES -------------------------------------------------------------'/
/'------------------------------------------------ PACKAGE HECHO -------------------------------------------------------------'/
class Hecho {
    - idEnFuente : Long
    - titulo : String
    - descripcion : String
    - categoria : Categoria
    - fechaDeAcontecimiento : LocalDate
    - fechaDeCargaDelHecho : LocalDateTime
    - lugar : Lugar
    - origen : OrigenDelHecho
    - solicitudesDeEliminacion : List<Solicitud>
    - esAnonimo : Boolean
    - etiquetas : List<Etiqueta>
    - multimedia : List<Multimedia>
    - fueEliminado : Boolean
    - usuarioContribuyente : Usuario
    - idAgregador : Long
}

class Categoria {
    - nombre : String
}

class Etiqueta {
    - nombre : String
    - descripcion : String
}

class Lugar {
    - latitud : Double
    - longitud : Double
}

class Multimedia {
    - rutaAlArchivo : String
}

enum OrigenDelHecho {
    FUENTEDINAMICA,
    FUENTEESTATICA,
    FUENTEPROXY
}

/'------------------------------------------------ TERMINA PACKAGE HECHO -------------------------------------------------------------'/

/'------------------------------------------------ EMPIEZA PACKAGE SOLICITUD -------------------------------------------------------------'/
class Solicitud {
    - id : Long
    - justificacionDeEliminacion : String
    - hecho : Hecho
    - estado : EstadoDeSolicitudDeEliminacion
    - fechaDeCargaDeSolicitud : LocalDateTime
    - fechaDeEvaluacionDeSolicitud : LocalDateTime
    - visitanteQueCargoLaSolicitud : Usuario
    - historialSolicitud : List<HistorialSolicitud>
    - detectorDeSpam : DetectorDeSpam

    + actualizarHistorialDe(Solicitud unaSolicitud, Usuario usuarioModificador) : void
}

class HistorialSolicitud {
    - estado : EstadoDeSolicitudDeEliminacion
    - fechaModificacion : LocalDateTime
    - usuarioModificador : Usuario
}

enum EstadoDeSolicitudDeEliminacion {
    PENDIENTE,
    RECHAZADA,
    APROBADA
}

/'------------------------------------------------ TERMINA PACKAGE SOLICITUD -------------------------------------------------------------'/

/'------------------------------------------------ EMPIEZA PACKAGE COLECCION -------------------------------------------------------------'/
class Coleccion {
    - titulo : String
    - descripcion : String
    - handle : String
    - hechos : List<Hecho>
    - fuentesDeHechos : List<FuenteDeHechos>
    - criterioDePertenencia : List<Criterio>

    + cumpleCriterios(Hecho unHecho, List<Criterio> criterios) : boolean
    + verificadorDeAgregadorDeHechos(Hecho unHecho) : boolean
    + contieneAlgunaSolicitudAprobada(Hecho unHecho) : boolean
}

class VerificadorDeCriterios {
    + cumpleCategoria(Hecho hecho, Categoria categoria) : boolean
    + cumpleLugar(Hecho hecho, Lugar lugar) : boolean
    + entreFechas(Hecho hecho, LocalDate desde, LocalDate hasta) : boolean
}

interface Criterio {
    + cumple(Hecho hecho) : boolean
}
/'------------------------------------------------ TERMINA PACKAGE COLECCION -------------------------------------------------------------'/

/'------------------------------------------------ EMPIEZA PACKAGE CRITERIOS -------------------------------------------------------------'/
class CriterioCategoria implements Criterio {
    - categoria : Categoria
    + cumple(Hecho hecho) : boolean
}

class CriterioFechaEntre implements Criterio {
    - desde : LocalDate
    - hasta : LocalDate
    + cumple(Hecho hecho) : boolean
}

class CriterioLugar implements Criterio {
    - lugar : Lugar
    + cumple(Hecho hecho) : boolean
}
/'------------------------------------------------ TERMINA PACKAGE CRITERIOS -------------------------------------------------------------'/
/'------------------------------------------------ TERMINA PACKAGE COLECCION -------------------------------------------------------------'/


/'------------------------------------------------ EMPIEZA PACKAGE USUARIO -------------------------------------------------------------'/
class Usuario {
    - nombre : String
    - idUsuario : Long
}
/'------------------------------------------------ TERMINA PACKAGE USUARIO -------------------------------------------------------------'/
/'------------------------------------------------ TERMINA PACKAGE ENTITIES -------------------------------------------------------------'/

/'------------------------------------------------ EMPIEZA PACKAGE FUENTES -------------------------------------------------------------'/
interface FuenteDeHechos {
    + obtenerHechos() : List<Hecho>
}

class FuenteDinamica implements FuenteDeHechos {
    - webClient : WebClient
    + obtenerHechos() : List<Hecho>
}

class FuenteEstatica implements FuenteDeHechos {
    - webClient : WebClient
    + obtenerHechos() : List<Hecho>
}

class FuenteProxy implements FuenteDeHechos {
    - urlHechos : String
    - pathUrl : String
    - webClient : WebClient
    + obtenerHechos() : List<Hecho>
}

/'------------------------------------------------ TERMINA PACKAGE FUENTES -------------------------------------------------------------'/
/'------------------------------------------------ EMPIEZA PACKAGE SPAM -------------------------------------------------------------'/
interface DetectorDeSpam {
    + esSpam(String texto) : boolean
}

class DetectorDeSpamImpl implements DetectorDeSpam {
    - PALABRAS_SPAM : List<String>
    - LONGITUD_MAXIMA_PARA_REVISION : Int
    - REPETICIONES_MAXIMAS_PERMITIDAS : Int
    + esSpam(String unaJustificacion) : boolean
    + esRepeticionExcesiva(String unTexto) : boolean

}
/'------------------------------------------------ TERMINA PACKAGE SPAM -------------------------------------------------------------'/


/'----------------------------------------------------- RELACIONES -------------------------------------------------------------'/
Hecho -r-> Categoria
Hecho -r-> Lugar
Hecho -r-> OrigenDelHecho
Hecho -d-> Usuario
Hecho -d-> Solicitud
Hecho -d-> Etiqueta
Hecho -d-> Multimedia


' ========== SOLICITUD ==========
Solicitud -r-> Hecho
Solicitud -r-> EstadoDeSolicitudDeEliminacion
Solicitud -r-> Usuario
Solicitud -d-> HistorialSolicitud
Solicitud -r-> DetectorDeSpam

HistorialSolicitud -r-> EstadoDeSolicitudDeEliminacion
HistorialSolicitud -r-> Usuario

' ========== COLECCION ==========
Coleccion -d-> Hecho
Coleccion -r-> FuenteDeHechos
Coleccion -r-> Criterio

' ========== CRITERIOS ==========
CriterioCategoria -r-> Categoria
CriterioLugar -r-> Lugar

' ========== VERIFICADOR ==========
VerificadorDeCriterios -r-> Hecho
VerificadorDeCriterios -r-> Categoria
VerificadorDeCriterios -r-> Lugar








@enduml