@startuml
'https://plantuml.com/class-diagram

entity "hecho" as hechos {
  * id : INTEGER(11) «PK»
 * categoria_id : INTEGER(11) «FK»
  --
  titulo : VARCHAR(255)
  descripcion : TEXT
  fecha_acontecimiento: DATE
  fecha_carga: DATE
  origen : ENUM(DATASET, CARGA_MANUAL, CONTRIBUYENTE)
}

entity "hecho_multimedia" as hechos_multimedia {
  * hecho_id : INTEGER(11) «FK»
  --
  url: VARCHAR(255)
}

entity "lugar" as lugares {
  * id : INTEGER(11) «PK»
  --
  fecha : date
  total : decimal
}

entity "categoria" as categorias {
  *id : INTEGER(11) «PK»
  --
  nombre : VARCHAR(100)
}

hechos ||--|| lugares
categorias ||--{ hechos
hechos ||--o{ hechos_multimedia

@enduml

