##spring.application.name=cliente-liviano
##server.port=8085
##hechos.upload.dir=uploads
##hechos.upload.url-path=/uploads/**
##gateway.url = http://localhost:8090

spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}
hechos.upload.dir=${HECHOS_UPLOAD_DIR}
hechos.upload.url-path=${HECHOS_UPLOAD_URL_PATH}
gateway.url=${GATEWAY_URL}

