@startuml

class Revision {
  - estado : EstadoRevision
  - comentario : String
  + estaPendiente() : boolean
}
class Multimedia {
  - rutaAlArchivo : String
}
class Categoria {
  - nombre : String
}
class Lugar {
  - latitud : Double
  - longitud : Double
}
class Etiqueta {
  - nombre : String
  - descripcion : String
}
class Hecho {
  - id : Integer
  - titulo : String
  - descripcion : String
  - categoria : Categoria
  - fechaDeAcontecimiento : LocalDate
  - fechaDeCarga : LocalDateTime
  - lugar : Lugar
  - origen : OrigenDelHecho
  - solicitudesDeEliminacion : List<Solicitud>
  - etiquetas : List<Etiqueta>
  - multimedia : List<String>
  - contribuyente : Usuario
  - revision : Revision
  + tieneMultimedia() : boolean
  + agregarEtiquetas(Etiqueta... unasEtiquetas) : void
  + agregarSolicitudDeEliminacion(Solicitud unaSolicitud) : void
  + tieneSolicitudesDeEliminacionAprobada() : boolean
  + esEditable() : boolean
  + esAnonimo() : boolean
}
class HistorialSolicitud {
  - estado : EstadoDeSolicitudDeEliminacion
  - fechaModificacion : LocalDateTime
  - administradorModificador : Administrador
}
class Solicitud {
  - id : Integer
  - justificacionDeEliminacion : String
  - hecho : Hecho
  - fechaSolicitud : LocalDateTime
  - fechaDeEvaluacionDeSolicitud : LocalDateTime
  - visitanteQueCargoLaSolicitud : Usuario
}
class FiltroPorLugar {
  - lugar : Lugar
  + aplica(Hecho hecho) : boolean
}
class FiltroPorAnonimato {
  - esAnonimo : boolean
  + aplica(Hecho hecho) : boolean
}
class FiltroPorCategoria {
  - categoria : Categoria
  + aplica(Hecho hecho) : boolean
}
class FiltroPorEtiqueta {
  - etiqueta : Etiqueta
  + aplica(Hecho hecho) : boolean
}
interface FiltroHecho {
}


FiltroPorLugar ..|> FiltroHecho
FiltroPorAnonimato ..|> FiltroHecho
FiltroPorCategoria ..|> FiltroHecho
FiltroPorEtiqueta ..|> FiltroHecho
FiltroHecho ..> Hecho

Hecho --> Categoria
Hecho --> Lugar
Hecho --> Etiqueta
Hecho --> Revision
Hecho --> Multimedia


Solicitud --> Hecho
Solicitud --> HistorialSolicitud

@enduml