spring.application.name=FuenteDinamica
server.port=8081
hechos.upload.dir=uploads
hechos.upload.url-path=/uploads/**
spring.jackson.serialization.write-dates-as-timestamps=false

spring.datasource.url=jdbc:mysql://localhost:3306/fuenteDinamica_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
