@startuml
class Hecho {
    - id : Long
    - titulo : String
    - descripcion : String
    - categoria : Categoria
    - lugar : Lugar
    - fechaDeAcontecimiento : LocalDate
    - fechaDeCarga : LocalDateTime
    - multimedia : List<Multimedia>
    - origen : OrigenDelHecho
}

class Categoria {
    - nombre : String
}

class Lugar {
    - latitud : Double
    - longitud : Double
}

class Multimedia {
    - rutaAlArchivo : String
}

enum OrigenDelHecho {
    DATASET,
    CARGA_MANUAL,
    CONTRIBUYENTE
}

interface Importador {
    + importarHechos(String archivo) : List<Hecho>
}

class LectorCSV{
    + leerCSV(String archivo) : List<String[]>
}

class importadorCSV implements Importador{
    - lectorCSV : LectorCSV

    + importarHechos(String archivo) : List<HechoInputDTO>
}



Hecho --> Lugar
Hecho --> Multimedia
Hecho --> OrigenDelHecho
Hecho --> Categoria
importadorCSV --> LectorCSV



@enduml