spring.application.name=Agregador
hechos.upload.dir=uploads
hechos.upload.url-path=/uploads/**
spring.jackson.serialization.write-dates-as-timestamps=false

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=${SERVER_PORT}

management.endpoints.web.exposure.include=*

management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.api-key=e106ceff48cb70c8b2cc1a183c2cb02d
management.datadog.metrics.export.site=us5.datadoghq.com
management.datadog.metrics.export.step=10s

dd.service=agregador
dd.env=dev

management.endpoint.health.show-details=always

fuente.estatica.base-url=http://localhost:8090/api/fuente-estatica