@startuml
'https://plantuml.com/class-diagram
'El titulo podria ser un posible enum

class Coleccion{
    - titulo : String
    - descripcion : String
    - hechos : List<Hecho>

    + crearColeccion() : ¿void?
}

abstract class Hecho{
  - publicador : Usuario
  - titulo : String
  - descripcion : String
  - categoria : Enum
  - fechaDelAcontecimiento : LocalDateTime
  - lugarDelAcontecimiento : Lugar
  - origen : Origen
  - etiqueta : Etiqueta
}

class HechoDeTexto extends Hecho{
}

class HechoMultimedia extends Hecho{
 - ???? contenidoMultimedia
}

class Lugar{
    - nombre : String
    - latitud : Float
    - longitud : Float
}

interface OrigenDelHecho {
    cargarHecho(Hecho unHecho) : void
}

class CargaManual implements OrigenDelHecho {
    cargarHecho(Hecho unHecho) : void
}

class Dataset implements OrigenDelHecho {
    cargarHecho(Hecho unHecho) : void
}

class Contribuyente implements OrigenDelHecho {
    cargarHecho(Hecho unHecho) : void
}

abstract class Usuario{
    - nombre : String
    - apellido : String
    - edad : Integer
    - tipoDeUsuario : TipoDeUsuario
    + void subirHecho(Hecho unHecho)
    + void solicitarBorrarHecho(Hecho unHecho)
    + void buscarHecho(Hecho unHecho)
}

enum TipoDeUsuario {
    CONTRIBUYENTE,
    VISUALIZADOR
}

class Solicitud{
    - justificacion : String
    - estadoDeSolicitud : EstadoDeSolicitudDeEliminacion
}

enum EstadoDeSolicitudDeEliminacion {
    PENDIENTE,
    APROBADA,
    RECHAZADA
}

class Administrador{
   + crearColeccion(Coleccion unaColeccion) : void
   + importarHecho(??? archivo) : void
   + aceptarSolicitud(Solicitud solicitud) : void
   + eliminarSolicitud(Solicitud solicitud) : void
}

Hecho --> Usuario
Lugar o-l- Hecho
Coleccion -->"*" Hecho
Administrador -->"*" Solicitud
Administrador --> Coleccion
Usuario --> Solicitud
EstadoDeSolicitudDeEliminacion o-u- Solicitud
TipoDeUsuario o-u- Usuario
OrigenDelHecho o-- Hecho

@enduml