@startuml
'https://plantuml.com/class-diagram

package "coleccion" {
    class Categoria {
        - nombre : String
    }

    class Coleccion {
        - titulo : String
        - descripcion : String
        - hechos : Map<String, Hecho>
        - criterioDePertenencia : List<CriterioDePertenencia>

        + agregarHecho(Hecho hecho) : void
        + eliminarHecho(Hecho unHecho) : void
        + agregarCriterioDePertenencia(CriterioDePertenencia criterio) : void
        + eliminarHechoPorSolicitudDeEliminacionAprobada(Hecho unHecho) : void
    }


    interface CriterioDePertenencia {
        + cumple(Hecho unHecho) : boolean
    }
}


package "hecho" {
    package "etiqueta" {
        class Etiqueta {
            - nombre : String
            - descripcion : String
        }
    }

    package "filtroHecho" {
        interface FiltroHecho {
            + aplica(Hecho unHecho) : boolean
        }

        class FiltroPorAnonimato implements FiltroHecho {
            - esAnonimo : boolean

            + aplica(Hecho unHecho) : boolean
        }

        class FiltroPorCategoria implements FiltroHecho {
            - categoria : Categoria

            + aplica(Hecho unHecho) : boolean
        }

        class FiltroPorEtiqueta implements FiltroHecho {
            - etiqueta : Etiqueta

            + aplica(Hecho unHecho) : boolean
        }

        class FiltroPorLugar implements FiltroHecho {
            - lugar : Lugar

            + aplica(Hecho unHecho) : boolean
        }
    }

    package "gestorDeHechos" {
        class GestorDeHechos {
            + cargarHecho(Hecho unHecho) : void
        }
    }

    package "lugar" {
        class Lugar {
            - nombre : String
            - latitud : Double
            - longitud : Double
        }
    }

    package "solicitudes" {
        enum EstadoDeSolicitudDeEliminacion {
            PENDIENTE,
            APROBADA,
            RECHAZADA
        }

        class GestorDeSolicitudes {
            - solicitudesDeEliminacionDeHecho : List<Solicitud>

            + aprobarSolicitud(Solicitud unaSolicitud) : void
            + rechazarSolicitud(Solicitud unaSolicitud) : void
            + eliminarSolicitudDeLista(Solicitud unaSolicitud) : void
            + esValida(Solicitud unaSolicitud) : boolean
        }

        class Solicitud {
            - justificacionDeEliminacion : String
            - hecho : Hecho
            - estado : EstadoDeSolicitudDeEliminacion
            - fechaSolicitud : LocalDateTime
        }
    }

    class Hecho {
        - titulo : String
        - descripcion : String
        - categoria : Categoria
        - fechaDeAcontecimiento : LocalDate
        - fechaDeCarga : LocalDateTime
        - lugar : Lugar
        - origen : OrigenDelHecho
        - solicitudesDeEliminacion : List<Solicitud>
        - esAnonimo : Boolean
        - etiqueta : Etiqueta
        - multimedia : List<Multimedia>

        + tieneMultimedia() : boolean
        + agregarEtiquetas(Etiqueta ... unasEtiquetas) : void
        + agregarSolicitudesDeEliminacion(Solicitud unaSolicitud) : void
        + tieneSolicitudesDeEliminacionAprobada() : boolean
    }

    class Multimedia {
    }

    enum OrigenDelHecho {
        DATASET,
        CARGA_MANUAL,
        CONTRIBUYENTE;
    }
}

package "users" {
     class Administrador {
        - nombre: String
        - gestorDeSolicitudes: GestorDeSolicitudes
        - importador: Importador

        + elegirImportador(Importador importador): void
        + importarHechos(): Coleccion
        + aprobarSolicitud(Solicitud unaSolicitud): void
        + rechazarSolicitud(Solicitud unaSolicitud): void
        }

    enum TipoDeVisitante {
        VISUALIZADOR,
        CONTRIBUYENTE
    }

    class Visitante {
        - nombre: String
        - apellido: String
        - edad: Integer
        # tipoDeVisitante: TipoDeVisitante
        - gestorDeHechos: GestorDeHechos

        + subirHecho(Hecho unHecho): void
        + solicitarBorrarUnHecho(Hecho unHecho): void
        + filtrar(Coleccion coleccion, FiltroHecho filtro): List<Hecho>
}

package "utils.importador" {

    class Config {
        - static final ARCHIVO_CONFIG : String
        - static final props : Properties


        + static String get(String clave)
        }

    interface Importador {
        + void importarHechos(String archivo, Coleccion coleccion)
    }

    class ImportadorCSV implements Importador {
        + void importarHechos(String archivo, Coleccion coleccion)
    }

}


Lugar o-l- Hecho
Coleccion --> "*" Hecho
GestorDeSolicitudes --> "*" Solicitud
Administrador --> GestorDeSolicitudes
Administrador --> Importador
EstadoDeSolicitudDeEliminacion o-u- Solicitud
OrigenDelHecho o-- Hecho
Visitante ..> FiltroHecho
Hecho --> "*" Solicitud
Hecho --> Categoria
Hecho o--> Etiqueta
Visitante --> GestorDeSolicitudes
Visitante --> TipoDeVisitante
Visitante ..> Hecho
Hecho --> "*" Multimedia
Visitante--> GestorDeHechos
GestorDeHechos..>Hecho
Coleccion-->CriterioDePertenencia
Administrador..>Config
@enduml