@startuml


package "Colecciones" {
class Coleccion {
    - titulo : String
    - descripcion : String
    - hechos : List<Hecho>

    + agregarHechos(Hecho ... unosHechos) : void
    + eliminarHecho(Hecho unHecho) : void
}

class Categoria {
    - nombre : String
}

}

package "Hechos" {
interface FiltroHecho {
    + aplica(Hecho unHecho) : boolean
}

class FiltroHechoPorAnonimato implements FiltroHecho {
    - esAnonimo : boolean

    + aplica(Hecho unHecho) : boolean
}

class FiltroHechoPorCategoria implements FiltroHecho {
    - esAnonimo : boolean

    + aplica(Hecho unHecho) : boolean
}

class FiltroHechoPorLugar implements FiltroHecho {
    - esAnonimo : boolean

    + aplica(Hecho unHecho) : boolean
}



interface OrigenDelHecho {
    + cargarHecho(Hecho unHecho) : void
}

class CargaManual implements OrigenDelHecho {
    + cargarHecho(Hecho unHecho) : void
}

class Contribuyente implements OrigenDelHecho {
    + cargarHecho(Hecho unHecho) : void
}

class DataSet implements OrigenDelHecho {
    + cargarHecho(Hecho unHecho) : void
}




abstract class Hecho {
    # titulo : String
    # descripcion : String
    # categoria : Categoria
    # fechaDeAcontecimiento : LocalDateTime
    # fechaDeCarga : LocalDateTime
    # lugar : Lugar
    # origen : OrigenDelHecho
    # solicitudesDeEliminacion : List<Solicitud>
    # esAnonimo : Boolean
    # etiqueta : Etiqueta

    + void agregarSolicitudDeEliminacion(Solicitud unaSolicitud)
}

class Etiqueta {
    - nombre : String
    - descripcion : String
}

class HechoDeTexto extends Hecho {
}


class Solicitud {
    - justificacion : String
    - hecho : Hecho
    - estado : EstadoDeSolicitudDeEliminacion
}

enum EstadoDeSolicitudDeEliminacion {
    PENDIENTE,
    APROBADA,
    RECHAZADA
}

class Lugar {
    - nombre : String
    - latitud : Double
    - longitud : Double
}

}

package "Repositorio De Hechos Dinamico" {
class RepositorioHechosDinamicos {
    - hechosSubidos : List<Hecho>

    + agregarHechos(Hecho ... unosHechos) : void
}

}

package "Usuarios" {
class Administrador {
    - nombre : String
    - solicitudesDeEliminacion : List<Solicitud>

    + importarHecho(Coleccion unaColeccion, String unaRutaDeArchivo) : void
    + crearColeccion(String unTitulo, String unaDescripcion) : Coleccion
    + getSolicitudesDeEliminacionPendientes() : List<Solicitud>
    + solicitudesValidas() : List<Solicitud>
    + evaluarSolicitud() : void
    + aprobarSolicitud(Solicitud unaSolicitud) : void
    + rechazarSolicitud(Solicitud unaSolicitud) : void
}

class Usuario {
    - nombre : String
    - apellido : String
    - edad : Integer
    - tipoDeUsuario : TipoDeUsuario

    + subirHecho(Hecho unHecho) : void
    + solicitarBorrarUnHecho(Hecho unHecho) : void
    + visualizar(Coleccion unaColeccion) : void
    + navegar(Coleccion unaColeccion, FiltroHecho unFiltro) : void
}

enum TipoDeUsuario {
    CONTRIBUYENTE,
    VISUALIZADOR
}

}



'------------------- RELACIONES -----------------------'

'RELACIONES DE PACKAGE HECHOS'
Hecho -r-> "*" Solicitud
FiltroHecho *-- Hecho
EstadoDeSolicitudDeEliminacion *-- Hecho
OrigenDelHecho *-r- Hecho
Lugar *-- Hecho
Etiqueta *-- Hecho


'RELACIONES DE PACKAGE USUARIOS'
Usuario --> TipoDeUsuario

'RELACIONES DE PACKAGE COLECCIONES'
Coleccion -l-> Categoria


'RELACIONES ENTRE PACKAGES'
Coleccion --> "*" Hecho
Administrador --> "*" Solicitud
RepositorioHechosDinamicos --> "*" Hecho
Usuario ..> Hecho





@enduml